# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Victoria Catalina\Documents\GitHub\Trabajo-Final\InformacionPaciente.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(324, 548)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 55, 21))
        self.label_2.setObjectName("label_2")
        self.NombrePaciente = QtWidgets.QLineEdit(Dialog)
        self.NombrePaciente.setGeometry(QtCore.QRect(100, 60, 113, 22))
        self.NombrePaciente.setObjectName("NombrePaciente")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 55, 16))
        self.label_3.setObjectName("label_3")
        self.CedulaPaciente = QtWidgets.QLineEdit(Dialog)
        self.CedulaPaciente.setGeometry(QtCore.QRect(100, 100, 113, 22))
        self.CedulaPaciente.setObjectName("CedulaPaciente")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 55, 16))
        self.label_4.setObjectName("label_4")
        self.EdadPaciente = QtWidgets.QLineEdit(Dialog)
        self.EdadPaciente.setGeometry(QtCore.QRect(100, 140, 113, 22))
        self.EdadPaciente.setText("")
        self.EdadPaciente.setObjectName("EdadPaciente")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 400, 71, 16))
        self.label_5.setObjectName("label_5")
        self.DiagnosticoPaciente = QtWidgets.QLineEdit(Dialog)
        self.DiagnosticoPaciente.setGeometry(QtCore.QRect(110, 400, 113, 22))
        self.DiagnosticoPaciente.setObjectName("DiagnosticoPaciente")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(40, 260, 55, 16))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.SALIR = QtWidgets.QPushButton(Dialog)
        self.SALIR.setGeometry(QtCore.QRect(120, 470, 93, 28))
        self.SALIR.setObjectName("SALIR")
        self.ImagenPaciente = QtWidgets.QLabel(Dialog)
        self.ImagenPaciente.setGeometry(QtCore.QRect(50, 200, 221, 161))
        self.ImagenPaciente.setObjectName("ImagenPaciente")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "DATOS DEL PACIENTE"))
        self.label_2.setText(_translate("Dialog", "Nombre:"))
        self.label_3.setText(_translate("Dialog", "Cedula:"))
        self.label_4.setText(_translate("Dialog", "Edad:"))
        self.label_5.setText(_translate("Dialog", "Diagnostico:"))
        self.SALIR.setText(_translate("Dialog", "SALIR"))
        self.ImagenPaciente.setText(_translate("Dialog", "TextLabel"))
