# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Victoria Catalina\Documents\GitHub\Trabajo-Final\Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(284, 255)
        self.centralwidget = QtWidgets.QWidget(Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.Agregar_Paciente = QtWidgets.QPushButton(self.centralwidget)
        self.Agregar_Paciente.setGeometry(QtCore.QRect(70, 50, 151, 31))
        self.Agregar_Paciente.setObjectName("Agregar_Paciente")
        self.Buscar_Paciente = QtWidgets.QPushButton(self.centralwidget)
        self.Buscar_Paciente.setGeometry(QtCore.QRect(70, 110, 151, 31))
        self.Buscar_Paciente.setObjectName("Buscar_Paciente")
        Menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 284, 26))
        self.menubar.setObjectName("menubar")
        Menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Menu)
        self.statusbar.setObjectName("statusbar")
        Menu.setStatusBar(self.statusbar)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "MainWindow"))
        self.Agregar_Paciente.setText(_translate("Menu", "AGREGAR PACIENTE"))
        self.Buscar_Paciente.setText(_translate("Menu", "BUSCAR PACIENTE"))
